// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	domain "rest-api/domain"

	mock "github.com/stretchr/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// Add provides a mock function with given fields: book
func (_m *Database) Add(book domain.Book) string {
	ret := _m.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(domain.Book) string); ok {
		r0 = rf(book)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAll provides a mock function with given fields: filters
func (_m *Database) GetAll(filters map[string]interface{}) []domain.Book {
	ret := _m.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Book
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []domain.Book); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Book)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Database) GetByID(id string) (domain.Book, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.Book, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Book); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Book)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveByID provides a mock function with given fields: id
func (_m *Database) RemoveByID(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: hash, book
func (_m *Database) Update(hash string, book domain.Book) {
	_m.Called(hash, book)
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}